MODULE pbo_9000 OUTPUT.
SET PF-STATUS 'S9000'.
SET TITLEBAR 'T9000'.
ENDMODULE.

MODULE pai_9000 INPUT.
  CASE sy-ucomm.
    WHEN 'SAVE'.
      PERFORM criar_cliente.
    WHEN 'BACK'.
      LEAVE TO SCREEN 0.
    WHEN OTHERS.
  ENDCASE.

ENDMODULE.
